/******************************************************************************
 *
 * Name:	RTC.h
 * Project:	Hermon-2
 * Purpose:	Testing
 *
 ******************************************************************************/

/******************************************************************************
 *
 *  (C)Copyright 2005 - 2008 Marvell. All Rights Reserved.
 *
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into
 *  products for purposes authorized by the license agreement provided they
 *  include this notice and the associated copyright notice with any such
 *  product.
 *  The information in this file is provided "AS IS" without warranty.
 *
 ******************************************************************************/

/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	RTC.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_RTC_H
#define	__INC_RTC_H


/*
 *
 *	THE BASE ADDRESSES
 *
 */
#define	RTC_BASE	0xD4010000

/*
 *
 *	THE REGISTER DEFINES
 *
 */
#define	RTC_CNR	(RTC_BASE+0x0000)	/* 32 bit	RTC Counter Register */
#define	RTC_AR	(RTC_BASE+0x0004)	/* 32 bit	RTC Alarm Register */
#define	RTC_SR	(RTC_BASE+0x0008)	/* 32 bit	RTC Status Register */
#define	RTC_TR	(RTC_BASE+0x000C)	/* 32 bit	RTC Trim Register */
#define	RTC_PR	(RTC_BASE+0x0010)	/* 32 bit	RTC Control Register */
#define	RTC_BRN	(RTC_BASE+0x0014)	/* RTC Backup Registers Start */

/*
 *
 *	THE BIT DEFINES
 *
 */
/*	RTC_CNR	0x0000	RTC Counter Register */
#define	RTC_CNR_TC_MSK		SHIFT0(0xffffffff)	/* Time Count */
#define	RTC_CNR_TC_BASE		0

/*	RTC_AR	0x0004	RTC Alarm Register */
#define	RTC_AR_AT_MSK		SHIFT0(0xffffffff)	/* Alarm time */
#define	RTC_AR_AT_BASE		0

/*	RTC_SR	0x0008	RTC Status Register */
/*		Bit(s) RTC_SR_RSRV_31_4 reserved */
#define	RTC_SR_HZE					BIT_3				/* 1-Hz interrupt enable */
/* RTC alarm interrupt enable */
#define	RTC_SR_ALE					BIT_2
/* 1-Hz rising-edge detected */
#define	RTC_SR_HZ					BIT_1
#define	RTC_SR_AL					BIT_0				/* RTC alarm detected */

/*	RTC_TR	0x000C	RTC Trim Register */
/* Locking bit for the trim value */
#define	RTC_TR_LCK					BIT_31
/*		Bit(s) RTC_TR_RSRV_30_26 reserved */
#define	RTC_TR_D9_D0_MSK			SHIFT16(0x3ff)	/* Trim delete count */
#define	RTC_TR_D9_D0_BASE			16
#define	RTC_TR_C150_C0_MSK			SHIFT0(0xffff)	/* Clock divider count */
#define	RTC_TR_C150_C0_BASE			0

/*	RTC_PR	0x0010	RTC Control Register */
/*		Bit(s) RTC_PR_RSRV_31_1 reserved */
/* Controls the ALARM signal */
#define	RTC_PR_SW_ALARM				BIT_0

/*	RTC_BRn	0x0014	RTC Backup Registers */
#define	RTC_BRN_DATA_MSK		SHIFT0(0xffffffff)	/* Backup Data */
#define	RTC_BRN_DATA_BASE		0



/* -------------------- */


#endif	/* __INC_RTC_H */
