/******************************************************************************
 *
 * Name:	PMUD.h
 * Project:	Hermon-2
 * Purpose:	Testing
 *
 ******************************************************************************/

/******************************************************************************
 *
 *  (C)Copyright 2005 - 2008 Marvell. All Rights Reserved.
 *  
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended 
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the 
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into 
 *  products for purposes authorized by the license agreement provided they 
 *  include this notice and the associated copyright notice with any such
 *  product. 
 *  The information in this file is provided "AS IS" without warranty.
 *
 ******************************************************************************/

/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	PMUD.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_PMUD_H
#define	__INC_PMUD_H


/*
 *
 *	THE BASE ADDRESSES
 *
 */
#define	PMUD_BASE	0xFFA82000

/*
 *
 *	THE REGISTER DEFINES
 *
 */
#define	PMUD_DPCR	(PMUD_BASE+0x0000)	/* 32 bit	MSA Power Control Register */
#define	PMUD_DPSR	(PMUD_BASE+0x0008)	/* 32 bit	MSA Power Status Register */
#define	PMUD_DCGR	(PMUD_BASE+0x000C)	/* 32 bit	MSA Clock Gating Register */
#define	PMUD_DPRR	(PMUD_BASE+0x0018)	/* 32 bit	MSA Programmable Reset
										 *			Register
										 */
#define	PMUD_DRSR	(PMUD_BASE+0x001C)	/* 32 bit	MSA Reset Status Register */
#define	PMUD_DMPRX	(PMUD_BASE+0x0100)	/* MSA Module Power Register Start */

/*
 *
 *	THE BIT DEFINES
 *
 */
/*	PMUD_DPCR	0x0000	MSA Power Control Register */
#define	PMUD_DPCR_AXISD					BIT_31			/* AXISD */
#define	PMUD_DPCR_DSPSD					BIT_30			/* DSPSD */
#define	PMUD_DPCR_SLPEN					BIT_29			/* SLPEN */
#define	PMUD_DPCR_DTCMSD				BIT_28			/* DTCMSD */
#define	PMUD_DPCR_DDRCORSD				BIT_27			/* DDRCORSD */
#define	PMUD_DPCR_APBSD					BIT_26			/* APBSD */
#define	PMUD_DPCR_BBSD					BIT_25			/* BBSD */
/*		Bit(s) PMUD_DPCR_RSRV_24_20 reserved */
#define	PMUD_DPCR_VCTCXOSD				BIT_19			/* VCTCXOSD */
/*		Bit(s) PMUD_DPCR_RSRV_18_15 reserved */
#define	PMUD_DPCR_MSASLPEN				BIT_14			/* MSASLPEN */

/*	PMUD_DPSR	0x0008	MSA Power Status Register */
#define	PMUD_DPSR_AXIAVL				BIT_31				/* AXIAVL */
#define	PMUD_DPSR_APIDL					BIT_30				/* APIDL */
#define	PMUD_DPSR_CPIDL					BIT_29				/* CPIDL */
/*		Bit(s) PMUD_DPSR_RSRV_28 reserved */
#define	PMUD_DPSR_AP_FULL_IDLE			BIT_27				/* AP_FULL_IDLE */
#define	PMUD_DPSR_CP_FULL_IDLE			BIT_26				/* CP_FULL_IDLE */
#define	PMUD_DPSR_AP_SLEEP				BIT_25				/* AP_SLEEP */
#define	PMUD_DPSR_CP_SLEEP				BIT_24				/* CP_SLEEP */
/*		Bit(s) PMUD_DPSR_RSRV_23_0 reserved */

/*	PMUD_DCGR	0x000C	MSA Clock Gating Register */
#define	PMUD_DCGR_W_208M		BIT_31	/* W_208M */
#define	PMUD_DCGR_W_312M		BIT_30	/* W_312M */
/*		Bit(s) PMUD_DCGR_RSRV_29 reserved */
#define	PMUD_DCGR_G_LP52M		BIT_28	/* G_LP52M */
#define	PMUD_DCGR_G_LP26M		BIT_27	/* G_LP26M */
#define	PMUD_DCGR_G_104M		BIT_26	/* G_104M */
#define	PMUD_DCGR_G_78M			BIT_25	/* G_78M */
#define	PMUD_DCGR_G_52M			BIT_24	/* G_52M */
#define	PMUD_DCGR_G_48MHZ		BIT_23	/* G_48MHz */
#define	PMUD_DCGR_G_TWSI		BIT_22	/* G_TWSI */
#define	PMUD_DCGR_G_HFI2S		BIT_21	/* G_HFI2S */
#define	PMUD_DCGR_G_26M			BIT_20	/* G_26M */
#define	PMUD_DCGR_G_13M			BIT_19	/* G_13M */
#define	PMUD_DCGR_G_6_5M		BIT_18	/* G_6.5M */
#define	PMUD_DCGR_G_SUART		BIT_17	/* G_SUART */
/*		Bit(s) PMUD_DCGR_RSRV_16 reserved */
#define	PMUD_DCGR_APMU_624M		BIT_15	/* APMU_624M */
#define	PMUD_DCGR_APMU_PLL2		BIT_14	/* APMU_PLL2 */
#define	PMUD_DCGR_APMU_312M		BIT_13	/* APMU_312M */
#define	PMUD_DCGR_APMU_104M		BIT_12	/* APMU_104M */
#define	PMUD_DCGR_APMU_52M		BIT_11	/* APMU_52M */
#define	PMUD_DCGR_APMU_48M		BIT_10	/* APMU_48M */
/*		Bit(s) PMUD_DCGR_RSRV_9 reserved */
#define	PMUD_DCGR_AP_FUART		BIT_8	/* AP_FUART */
#define	PMUD_DCGR_AP_52M		BIT_7	/* AP_52M */
#define	PMUD_DCGR_AP_HSTWSI		BIT_6	/* AP_HSTWSI */
#define	PMUD_DCGR_AP_HFI2S		BIT_5	/* AP_HFI2S */
#define	PMUD_DCGR_AP_26M		BIT_4	/* AP_26M */
#define	PMUD_DCGR_AP_13M		BIT_3	/* AP_13M */
#define	PMUD_DCGR_AP_6_5M		BIT_2	/* AP_6.5M */
#define	PMUD_DCGR_AP_SUART		BIT_1	/* AP_SUART */
/*		Bit(s) PMUD_DCGR_RSRV_0 reserved */

/*	PMUD_DPRR	0x0018	MSA Programmable Reset Register */
/*		Bit(s) PMUD_DPRR_RSRV_31_4 reserved */
#define	PMUD_DPRR_BBR					BIT_3				/* BBR */
/*		Bit(s) PMUD_DPRR_RSRV_2_0 reserved */

/*	PMUD_DRSR	0x001C	MSA Reset Status Register */
/*		Bit(s) PMUD_DRSR_RSRV_31_12 reserved */
#define	PMUD_DRSR_SWR_MSK				SHIFT8(0xf)			/* SWR */
#define	PMUD_DRSR_SWR_BASE				8
/*		Bit(s) PMUD_DRSR_RSRV_7_4 reserved */
#define	PMUD_DRSR_MOHR					BIT_3				/* MohR */
#define	PMUD_DRSR_WDTR					BIT_2				/* WDTR */
/*		Bit(s) PMUD_DRSR_RSRV_1 reserved */
#define	PMUD_DRSR_POR					BIT_0				/* POR */

/*	PMUD_DMPRx	0x0100	MSA Module Power Register */
/*		Bit(s) PMUD_DMPRX_RSRV_31_3 reserved */
#define	PMUD_DMPRX_MSR					BIT_2				/* MSR */
#define	PMUD_DMPRX_AG					BIT_1				/* AG */
#define	PMUD_DMPRX_MCE					BIT_0				/* MCE */



/* -------------------- */


#endif	/* __INC_PMUD_H */
